services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      "IS_DOCKER": true
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "ASPNETCORE_Kestrel__Certificates__Default__Password": "mysecret"
      "ASPNETCORE_Kestrel__Certificates__Default__Path": "/https/aspnetapp.pfx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.aspnet/https:/https
